In [2]:
import pandas as pd
from utils.DataUnderstanding import DataUnderstanding

# Análise Exploratória:

## DataFrame:

In [3]:
path = r'../data/Dados Solução Casting.xlsx'
df = pd.read_excel(
    io=path
)

In [4]:
df.head(3)

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
0,B28DDB4B-8A49-4658-8539-5DA3F20AA39F,1000,D4758B39-E7EA-4D97-B6B1-6236CE2C05A2,BBEF56E1-66E0-47A6-95AC-5479DE79577B,2022-06-18,6768760F-758A-4B31-AE33-CEB127A956CB,7B6AD9C1-F745-4137-B62D-4A67E865E781,1,1.0,15.0,0.0,15.0,0.0,CASTING_DB108
1,8E22E8FC-65DC-44BA-AFFA-4D661108F0B4,1001,D4758B39-E7EA-4D97-B6B1-6236CE2C05A2,AF858E1C-9C72-4B63-AC51-A8185ECCCC35,2022-06-18,0136ECF4-9F4D-4DBE-A78D-B2ED565CE60C,7B6AD9C1-F745-4137-B62D-4A67E865E781,1,1.0,32.0,0.0,32.0,0.0,CASTING_DB108
2,E36DEDC5-78CB-4452-9E04-AD174E32747C,1002,D4758B39-E7EA-4D97-B6B1-6236CE2C05A2,BBEF56E1-66E0-47A6-95AC-5479DE79577B,2022-06-20,B0974005-D231-438C-A0C1-F6A211B00697,7B6AD9C1-F745-4137-B62D-4A67E865E781,1,1.0,15.0,0.0,15.0,0.0,CASTING_DB108

## Código:

In [5]:
class Casting(DataUnderstanding):
    pass

if __name__ == '__main__':
    casting = Casting()

## Entendimento dos dados:

In [6]:
df.head(3)

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
0,B28DDB4B-8A49-4658-8539-5DA3F20AA39F,1000,D4758B39-E7EA-4D97-B6B1-6236CE2C05A2,BBEF56E1-66E0-47A6-95AC-5479DE79577B,2022-06-18,6768760F-758A-4B31-AE33-CEB127A956CB,7B6AD9C1-F745-4137-B62D-4A67E865E781,1,1.0,15.0,0.0,15.0,0.0,CASTING_DB108
1,8E22E8FC-65DC-44BA-AFFA-4D661108F0B4,1001,D4758B39-E7EA-4D97-B6B1-6236CE2C05A2,AF858E1C-9C72-4B63-AC51-A8185ECCCC35,2022-06-18,0136ECF4-9F4D-4DBE-A78D-B2ED565CE60C,7B6AD9C1-F745-4137-B62D-4A67E865E781,1,1.0,32.0,0.0,32.0,0.0,CASTING_DB108
2,E36DEDC5-78CB-4452-9E04-AD174E32747C,1002,D4758B39-E7EA-4D97-B6B1-6236CE2C05A2,BBEF56E1-66E0-47A6-95AC-5479DE79577B,2022-06-20,B0974005-D231-438C-A0C1-F6A211B00697,7B6AD9C1-F745-4137-B62D-4A67E865E781,1,1.0,15.0,0.0,15.0,0.0,CASTING_DB108

In [7]:
df.tail(3)

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
65532,ADF59151-19C5-4B13-A81A-12FBB9346B41,152462-82-4dcf1591-5378-45a0-991a-d29b3e6209a3,FADCA1CC-2E3A-4278-BF58-F44F8D8940C9,7460ECC7-89E8-4D4E-961D-63E28B5A8D97,2022-05-23,21E2FB67-404C-43FE-8635-131F9FA4F9E9,38DBC0E7-BA05-4DBD-8397-81DD6C42CE12,0,1.0,160.00,0.0,160.00,0.0,CASTING_DB106
65533,50E63379-394B-43CA-9C01-C3E7F709C839,152463-22-df7662df-b21d-4edb-ae0b-a227c2c53943,CF4205F1-50A7-4013-925D-F20761AF2D82,E1613BD5-18FA-44B4-9F62-47444214C630,2022-05-24,8E400343-C57B-47C8-BDAD-83A98D2111B8,E9E1EBB9-BDFB-47C1-8E84-D584E8C531F7,1,1.0,14.98,0.0,14.98,0.0,CASTING_DB106
65534,561A9712-FFFC-43EE-BCD0-4372430876B5,152463-22-df7662df-b21d-4edb-ae0b-a227c2c53943,CF4205F1-50A7-4013-925D-F20761AF2D82,E1613BD5-18FA-44B4-9F62-47444214C630,2022-05-24,675250B1-F210-4EB8-B360-D9CE7F961CC0,38DBC0E7-BA05-4DBD-8397-81DD6C42CE12,0,1.0,54.98,0.0,54.98,0.0,CASTING_DB106

In [8]:
list(df.columns)

['VUF_CODIGO',
 'VUF_CODIGO_BOLETO',
 'UND_CODIGO',
 'FUN_CODIGO',
 'VUF_DT',
 'PRO_CODIGO',
 'CAT_CODIGO',
 'VUF_QTBOLETO',
 'VUF_QTPRODUTO',
 'VUF_VLRBRUTOVENDA',
 'VUF_VLRDESCONTO',
 'VUF_VLRLIQFINAL',
 'VUF_VLRTROCA',
 'CLV_BANCO']

In [9]:
casting.verificando_as_dimensões_do_dataframe(
    dataframe=df
)

Linhas: 65535
Colunas: 14

In [10]:
casting.descrição(
    dataframe=df,
    vertical=True
)

,count,mean,std,min,10%,15%,25%,50%,75%,85%,95%,99%,max
VUF_QTBOLETO,65535.0,0.47,0.50,0.00,0.00,0.00,0.00,0.0,1.00,1.0,1.0,1.00,1.0
VUF_QTPRODUTO,65535.0,1.00,3.39,-4.00,1.00,1.00,1.00,1.0,1.00,1.0,1.0,3.00,850.0
VUF_VLRBRUTOVENDA,65535.0,355.83,782.00,-15250.00,5.98,7.98,15.00,170.0,440.00,759.0,1499.0,3290.00,45900.0
VUF_VLRDESCONTO,65535.0,60.21,253.92,-8627.99,0.00,0.00,0.00,0.0,52.00,112.0,312.0,840.00,12450.0
VUF_VLRLIQFINAL,65535.0,295.62,619.81,-7326.00,5.00,6.98,13.98,144.0,359.98,640.0,1281.0,2719.66,45900.0
VUF_VLRTROCA,65535.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.0

In [11]:
casting.descrição_object(
    dataframe=df,
    vertical=True
)

                   count unique                                   top   freq
VUF_CODIGO         65535  65535  B28DDB4B-8A49-4658-8539-5DA3F20AA39F      1
VUF_CODIGO_BOLETO  65535  25693                                  1574    150
UND_CODIGO         65535     30  FADCA1CC-2E3A-4278-BF58-F44F8D8940C9  13920
FUN_CODIGO         65535    184  1F7A8D46-D0A3-45A6-B4FF-510CDB4E460B   3475
VUF_DT             65535    632                            2022-04-30   1286
PRO_CODIGO         62788  10126  08962C5F-8C97-4B24-91BB-F1C564558ABB   1886
CAT_CODIGO         65535     37  12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90  14289
CLV_BANCO          65535      2                         CASTING_DB108  37780

In [12]:
casting.verificando_tipos(
    dataframe=df
)

                     Tipos
VUF_CODIGO          object
VUF_CODIGO_BOLETO   object
UND_CODIGO          object
FUN_CODIGO          object
VUF_DT              object
PRO_CODIGO          object
CAT_CODIGO          object
VUF_QTBOLETO         int64
VUF_QTPRODUTO      float64
VUF_VLRBRUTOVENDA  float64
VUF_VLRDESCONTO    float64
VUF_VLRLIQFINAL    float64
VUF_VLRTROCA       float64
CLV_BANCO           object

In [13]:
casting.verificando_valores_nulos(
    dataframe=df
)

### Perguntas:

O que são esses valores negativos?

In [19]:
colunas = [
    'VUF_QTPRODUTO',
    'VUF_VLRBRUTOVENDA',
    'VUF_VLRDESCONTO',
    'VUF_VLRLIQFINAL',
]

for coluna in colunas:
    valores_negativos = df[(df[coluna] < 0)]

    print('====='*23)
    print(f'Coluna - {coluna}:')
    display(valores_negativos.head(2))

===================================================================================================================
Coluna - VUF_QTPRODUTO:

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
8,1A20DEB6-6A3C-467D-BC00-474C4CAE855A,1004,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,B75D3808-3646-46C0-B026-397748A89EA3,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-880.0,-280.0,-600.0,0.0,CASTING_DB108
15,76E3D732-1A92-488C-99EF-A77845F9A449,1006,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,5940ADC1-BD85-4C3B-BA5C-0EFD4F6CC496,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-699.0,-169.0,-530.0,0.0,CASTING_DB108

===================================================================================================================
Coluna - VUF_VLRBRUTOVENDA:

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
8,1A20DEB6-6A3C-467D-BC00-474C4CAE855A,1004,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,B75D3808-3646-46C0-B026-397748A89EA3,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-880.0,-280.0,-600.0,0.0,CASTING_DB108
15,76E3D732-1A92-488C-99EF-A77845F9A449,1006,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,5940ADC1-BD85-4C3B-BA5C-0EFD4F6CC496,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-699.0,-169.0,-530.0,0.0,CASTING_DB108

===================================================================================================================
Coluna - VUF_VLRDESCONTO:

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
8,1A20DEB6-6A3C-467D-BC00-474C4CAE855A,1004,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,B75D3808-3646-46C0-B026-397748A89EA3,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-880.0,-280.0,-600.0,0.0,CASTING_DB108
15,76E3D732-1A92-488C-99EF-A77845F9A449,1006,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,5940ADC1-BD85-4C3B-BA5C-0EFD4F6CC496,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-699.0,-169.0,-530.0,0.0,CASTING_DB108

===================================================================================================================
Coluna - VUF_VLRLIQFINAL:

,VUF_CODIGO,VUF_CODIGO_BOLETO,UND_CODIGO,FUN_CODIGO,VUF_DT,PRO_CODIGO,CAT_CODIGO,VUF_QTBOLETO,VUF_QTPRODUTO,VUF_VLRBRUTOVENDA,VUF_VLRDESCONTO,VUF_VLRLIQFINAL,VUF_VLRTROCA,CLV_BANCO
8,1A20DEB6-6A3C-467D-BC00-474C4CAE855A,1004,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,B75D3808-3646-46C0-B026-397748A89EA3,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-880.0,-280.0,-600.0,0.0,CASTING_DB108
15,76E3D732-1A92-488C-99EF-A77845F9A449,1006,A025C518-43FE-4793-91D9-8E964411B0B5,5CDB7660-FF19-42A0-A205-33CFC6E9BB0A,2022-07-15,5940ADC1-BD85-4C3B-BA5C-0EFD4F6CC496,12FDE7ED-AF3D-4EA5-8250-BBF2D0A5BB90,0,-1.0,-699.0,-169.0,-530.0,0.0,CASTING_DB108

De que forma esses valores podem influência em nossa análise?

In [15]:
for coluna in colunas:
    valores_negativos = df[(df[coluna] < 0)]

    descrição = {
        'qtd_negativos': valores_negativos.shape[0],
        'valor_total': valores_negativos[[coluna]].sum(),
        'maior_valor': valores_negativos[[coluna]].min()
    }
    print('=='*20)
    df_descrição = pd.DataFrame(descrição)
    display(df_descrição.T)

========================================

               VUF_QTPRODUTO
qtd_negativos         2249.0
valor_total          -2346.5
maior_valor             -4.0

========================================

               VUF_VLRBRUTOVENDA
qtd_negativos            2326.00
valor_total          -1764654.77
maior_valor            -15250.00

========================================

               VUF_VLRDESCONTO
qtd_negativos          1568.00
valor_total         -348333.54
maior_valor           -8627.99

========================================

               VUF_VLRLIQFINAL
qtd_negativos          2320.00
valor_total        -1416321.23
maior_valor           -7326.00